<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ActividadSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('actividades')->insert([
        //["sector_id"=>10,"codigo"=>"0011","detalle"=>"TIENDA DE BARRIO Y ABARROTES"],
        //["sector_id"=>10,"codigo"=>"0012","detalle"=>"CARNICERIAS"],
        //["sector_id"=>10,"codigo"=>"0013","detalle"=>"FRIALES"],
        //["sector_id"=>9,"codigo"=>"0018","detalle"=>"KIOSCOS"],
        // ["sector_id"=>10,"codigo"=>"0019","detalle"=>"AGENCIA DE REFRESCOS"],
        // ["sector_id"=>9,"codigo"=>"0021","detalle"=>"PANADERIAS INDEPENDIENTES"],
        // ["sector_id"=>9,"codigo"=>"0022","detalle"=>"JOYERIAS"],
        // ["sector_id"=>9,"codigo"=>"0025","detalle"=>"FABRICAS CONFITADOS Y PASANKALLAS"],
        // ["sector_id"=>1,"codigo"=>"0028","detalle"=>"MOLINOS DE CAFE"],
        // ["sector_id"=>1,"codigo"=>"0029","detalle"=>"MOLINOS DE CEREALES Y DE SAL"],
        // ["sector_id"=>9,"codigo"=>"0032","detalle"=>"PASTELERIA "],
        // ["sector_id"=>9,"codigo"=>"0033","detalle"=>"SALTEÑERIA "],
        // ["sector_id"=>9,"codigo"=>"0035","detalle"=>"CAFETERIAS Y HELADERIAS"],
        // ["sector_id"=>9,"codigo"=>"0036","detalle"=>"HAMBURGUESAS SNAKS Y OTROS"],
        ["sector_id"=>5,"codigo"=>"0037","detalle"=>"CLUB SOCIAL"],
        // ["sector_id"=>9,"codigo"=>"0038","detalle"=>"RESTAURANT "],
        // ["sector_id"=>12,"codigo"=>"0041","detalle"=>"COLCHONERIAS"],
        // ["sector_id"=>12,"codigo"=>"0042","detalle"=>"TALLER DE COSTURAS Y CONFECCION"],
        // ["sector_id"=>12,"codigo"=>"0043","detalle"=>"SASTRERIAS "],
        // ["sector_id"=>12,"codigo"=>"0044","detalle"=>"BORDADORES "],
        // ["sector_id"=>12,"codigo"=>"0045","detalle"=>"SOMBRERERIAS                            "],
        // ["sector_id"=>12,"codigo"=>"0046","detalle"=>"ZAPATERIAS "],
        // ["sector_id"=>10,"codigo"=>"0048","detalle"=>"OPTICAS    "],
        ["sector_id"=>9,"codigo"=>"0111","detalle"=>"LICORERIAS "],
        // ["sector_id"=>1,"codigo"=>"0116","detalle"=>"INDUSTRIAS TEXTIL DE TEJIDOS"],
        // ["sector_id"=>10,"codigo"=>"0118","detalle"=>"ALMACENES COMERCIALES Y ABARROTES"],
        ["sector_id"=>10,"codigo"=>"0119","detalle"=>"COMERCIO EN GRAL."],
        // ["sector_id"=>10,"codigo"=>"0122","detalle"=>"TIENDA DE COTILLONES"],
        // ["sector_id"=>10,"codigo"=>"0123","detalle"=>"TIENDA VENTA DE ROPA USADA"],
        // ["sector_id"=>10,"codigo"=>"0126","detalle"=>"COMPRA Y VENTA DE LANAS"],
        // ["sector_id"=>10,"codigo"=>"0129","detalle"=>"BAZARES Y TARJETERIAS"],
        // ["sector_id"=>9,"codigo"=>"0133","detalle"=>"COMISIONES Y CONSIGNACIONES"],
        // ["sector_id"=>10,"codigo"=>"0135","detalle"=>"FARMACIAS  "],
        // ["sector_id"=>9,"codigo"=>"0140","detalle"=>"REVISTERIAS"],
        // ["sector_id"=>10,"codigo"=>"0141","detalle"=>"MUEBLERIAS "],
        // ["sector_id"=>10,"codigo"=>"0143","detalle"=>"LIBRERIA, IMPRENTA, SERIGRAFIAS, SELLOS "],
        // ["sector_id"=>10,"codigo"=>"0147","detalle"=>"VIDRIERIAS "],
        // ["sector_id"=>11,"codigo"=>"0149","detalle"=>"EMPRESA MINERAS Y OTROS"],
        // ["sector_id"=>10,"codigo"=>"0152","detalle"=>"BARRACAS   "],
        // ["sector_id"=>10,"codigo"=>"0153","detalle"=>"MATERIALES DE CONSTRUCCION"],
        // ["sector_id"=>10,"codigo"=>"0154","detalle"=>"REPUESTO DE VEHICULOS"],
        ["sector_id"=>10,"codigo"=>"0155","detalle"=>"DISTRIBUIDORA IMPORTADORA"],
        // ["sector_id"=>10,"codigo"=>"0156","detalle"=>"REPUESTOS USADOS"],
        // ["sector_id"=>10,"codigo"=>"0157","detalle"=>"FERRETERIAS"],
        // ["sector_id"=>10,"codigo"=>"0161","detalle"=>"AGENCIA DE HUEVOS"],
        // ["sector_id"=>9,"codigo"=>"0163","detalle"=>"CLINICAS Y CENTROS MEDICOS"],
        // ["sector_id"=>9,"codigo"=>"0165","detalle"=>"EMBOLSADOS Y EMPAQUETADOS"],
        // ["sector_id"=>12,"codigo"=>"0213","detalle"=>"CURTIEMBRES"],
        // ["sector_id"=>12,"codigo"=>"0216","detalle"=>"ELABORACION DE VELAS, CERAS Y OTROS"],
        // ["sector_id"=>1,"codigo"=>"0221","detalle"=>"FABRICA DE TUBOS MOSAICOS Y LADRILLOS"],
        ["sector_id"=>1,"codigo"=>"0236","detalle"=>"EMBOTELLADORAS"],
       // ["sector_id"=>11,"codigo"=>"0238","detalle"=>"COMERCIALIZADORA MINERALES"],
        ["sector_id"=>1,"codigo"=>"0239","detalle"=>"INDUSTRIAS Y FABRICAS"],
        // ["sector_id"=>8,"codigo"=>"0310","detalle"=>"TOPOGRAFOS "],
        // ["sector_id"=>9,"codigo"=>"0312","detalle"=>"COMEDOR POPULAR Y POLLO A LA CANASTA"],
        // ["sector_id"=>9,"codigo"=>"0314","detalle"=>"PENSION Y ROTISERIA"],
        // ["sector_id"=>9,"codigo"=>"0315","detalle"=>"CHICHARRONERIAS Y FRICACERIAS"],
        ["sector_id"=>9,"codigo"=>"0316","detalle"=>"EXPENDIO DE CHICHAS"],
        ["sector_id"=>9,"codigo"=>"0317","detalle"=>"QUINTAS"],
        ["sector_id"=>5,"codigo"=>"0318","detalle"=>"WISQUERIAS,NIGTH CLUBS,KARAOKES Y V.B.  "],
        ["sector_id"=>9,"codigo"=>"0319","detalle"=>"CANTINAS NOCTURNAS"],
        // ["sector_id"=>5,"codigo"=>"0320","detalle"=>"LENOCINIOS Y MOTELES"],
        // ["sector_id"=>7,"codigo"=>"0322","detalle"=>"ALOJAMIENTOS, RESIDENCIALES Y POSADAS"],
        // ["sector_id"=>7,"codigo"=>"0323","detalle"=>"HOTELES    "],
        // ["sector_id"=>6,"codigo"=>"0326","detalle"=>"EMPRESA DE TRANSPORTES"],
        // ["sector_id"=>7,"codigo"=>"0330","detalle"=>"ALOJAMIENTO DE VEHICULOS"],
        // ["sector_id"=>9,"codigo"=>"0332","detalle"=>"ESTACION DE SERVICIOS"],
        // ["sector_id"=>9,"codigo"=>"0339","detalle"=>"CINES,FLETE DE VIDEOS Y AMPLIFICACION"],
        ["sector_id"=>5,"codigo"=>"0341","detalle"=>"DISCOTECAS "],
        ["sector_id"=>9,"codigo"=>"0343","detalle"=>"FRONTONES Y PISTAS"],
        // ["sector_id"=>9,"codigo"=>"0345","detalle"=>"RADIOS EMISORAS, TELEVISION Y CABLE"],
        // ["sector_id"=>9,"codigo"=>"0349","detalle"=>"CONJ. ELECTRONICOS Y BANDAS DE MÚSICA"],
        // ["sector_id"=>9,"codigo"=>"0350","detalle"=>"SALON DE BELLEZAS"],
        // ["sector_id"=>12,"codigo"=>"0351","detalle"=>"PELUQUERIAS"],
        // ["sector_id"=>10,"codigo"=>"0352","detalle"=>"ESTUDIO FOTOGRAFICO"],
        // ["sector_id"=>3,"codigo"=>"0353","detalle"=>"BANCOS"],
        // ["sector_id"=>3,"codigo"=>"0354","detalle"=>"BANCOS SUCURSALES"],
        // ["sector_id"=>3,"codigo"=>"0355","detalle"=>"ACTIVIDADES FINANCIERAS Y OTROS"],
        // ["sector_id"=>4,"codigo"=>"0358","detalle"=>"COMPANIA DE SEGUROS"],
        // ["sector_id"=>3,"codigo"=>"0360","detalle"=>"AGENCIAS ADUANERAS"],
        // ["sector_id"=>10,"codigo"=>"0361","detalle"=>"FUNERARIAS "],
        // ["sector_id"=>9,"codigo"=>"0362","detalle"=>"TINTORERIAS Y LAVANDERIAS"],
        // ["sector_id"=>8,"codigo"=>"0364","detalle"=>"BIOQUIMICOS, ANALISIS Y QUIMICOS"],
        // ["sector_id"=>1,"codigo"=>"0370","detalle"=>"EMPRESAS CONSTRUCTORAS Y OTROS"],
        // ["sector_id"=>9,"codigo"=>"0380","detalle"=>"INSTITUTOS ARTES MARCIALES"],
        // ["sector_id"=>10,"codigo"=>"0386","detalle"=>"SERVICIOS DE FOTOCOPIAS"],
        // ["sector_id"=>9,"codigo"=>"0389","detalle"=>"CONSULTORAS Y COMPUTACION"],
        // ["sector_id"=>9,"codigo"=>"0393","detalle"=>"SAUNAS Y DUCHAS"],
        // ["sector_id"=>8,"codigo"=>"0394","detalle"=>"INGENIEROS CIVILES"],
        // ["sector_id"=>8,"codigo"=>"0396","detalle"=>"ARQUITECTOS"],
        // ["sector_id"=>8,"codigo"=>"0397","detalle"=>"MEDICOS CIRUJANOS"],
        // ["sector_id"=>8,"codigo"=>"0399","detalle"=>"DENTISTAS Y ODONTOLOGOS"],
        // ["sector_id"=>12,"codigo"=>"0414","detalle"=>"TALLER DE TAPICERIA Y TALABARTERIA"],
        // ["sector_id"=>12,"codigo"=>"0416","detalle"=>"CARPINTERIAS"],
        // ["sector_id"=>12,"codigo"=>"0418","detalle"=>"RELOJERIAS "],
        // ["sector_id"=>1,"codigo"=>"0420","detalle"=>"INDUSTRIA Y METAL MECANICA"],
        // ["sector_id"=>9,"codigo"=>"0421","detalle"=>"MECANICAS, SOLDADURAS, CHAPA Y PINTURA"],
        // ["sector_id"=>12,"codigo"=>"0422","detalle"=>"TALLER ELECTRICOS"],
        // ["sector_id"=>12,"codigo"=>"0424","detalle"=>"HERRERIAS  "],
        // ["sector_id"=>9,"codigo"=>"0425","detalle"=>"MAESTRANZAS"],
        // ["sector_id"=>12,"codigo"=>"0429","detalle"=>"TALLER DE LLANTERIAS"],
        // ["sector_id"=>12,"codigo"=>"0431","detalle"=>"REPARADORA DE MOTOCICLETAS Y BICICLETAS "],
        // ["sector_id"=>12,"codigo"=>"0432","detalle"=>"TECNICOS DE RADIO Y TELVISION"],
        // ["sector_id"=>12,"codigo"=>"0436","detalle"=>"ARTESANIAS EN GENERAL"],
        // ["sector_id"=>9,"codigo"=>"0440","detalle"=>"TALLER DE REP. DE VEHICULOS Y RADIADORES"],
        // ["sector_id"=>12,"codigo"=>"0442","detalle"=>"TALLER DIVERSOS Y HOJALATERIAS"],
        ["sector_id"=>2,"codigo"=>"0443","detalle"=>"FABRICAS DE CHICHA"],
        // ["sector_id"=>10,"codigo"=>"0552","detalle"=>"FERIAS COMERCIALES"],
        // ["sector_id"=>8,"codigo"=>"3106","detalle"=>"ABOGADOS"],
        // ["sector_id"=>8,"codigo"=>"3107","detalle"=>"AUDITORES FINANCIEROS"],
        // ["sector_id"=>8,"codigo"=>"3109","detalle"=>"CONTADORES "],
        // ["sector_id"=>8,"codigo"=>"3113","detalle"=>"POSTAS SANITARIAS Y VETERINARIOS"],
        ["sector_id"=>9,"codigo"=>"3123","detalle"=>"SALON DE FIESTA"],
        //["sector_id"=>9,"codigo"=>"3126","detalle"=>"GESTORES LIBRECAMBISTAS OTROS"],
        ["sector_id"=>9,"codigo"=>"3914","detalle"=>"BAR PENSION"]]);
    }
}
